### ISSUE TITLE
AssertionError，assert protein.num_residue.item() == len(active_site)

### ISSUE THREAD

**Issue by chen-15969746967** [wangxr0526/EasIFA#8]
I had successfully run it before, but I don't know why it suddenly doesn't work again. I hope to get your help, thank you

File "/EasIFA/data_loaders/enzyme_rxn_dataloader.py", line 257, in get_item
    assert protein.num_residue.item() == len(active_site)
AssertionError

**Comment by wangxr0526** [comment]
This issue is related to the input sample. The enzyme structure you provided may contain non-standard amino acids or amino acid nodes that cannot be processed by RDKit, or the sequence length may exceed the processing limit of ESM, resulting in enzyme sequence truncation. In such cases, the counted amino acid sequence length may vary. Currently, EasIFA throws such unprocessable samples as errors. In the future, we will work to incorporate non-standard amino acids and more cases into the calculations to support predictions for more edge cases.

**Comment by wangxr0526** [comment]
I just remembered that I encountered this issue once before as well. In my case, the reason was that I hadn't installed gcc and g++ on the new system (I was using a Python environment extracted directly with conda unpack), which prevented torch_extensions from compiling, resulting in empty outputs. I'm not sure if you're facing the same issue.

**Comment by chen-15969746967** [comment]
I have installed gcc and g++, but this error persists
